version: '3.8'

services:
  # Data initialization - generates visualization data if missing
  data-init:
    build:
      context: .
      dockerfile: docker/Dockerfile.preprocessor
    volumes:
      - ./data/docker:/app/data:rw
    env_file:
      - .env
    networks:
      - atm-network
    restart: "no"
    healthcheck:
      test: ["CMD", "test", "-f", "/app/data/visualization.bin"]
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 2000s 

  # Main application - waits for data to be ready
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "3000:3000"
    volumes:
      - ./data/docker:/app/data:rw
    env_file:
      - .env
    networks:
      - atm-network
    restart: unless-stopped
    depends_on:
      data-init:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/metadata"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  atm-network:
    driver: bridge
